contexts = {
    1: "The driver wants to adjust the car seat heater to a comfortable temperature during a winter drive. The driver will seek assistance from the car AI for this.",
    2: "The driver wants to set the air conditioning to a specific temperature to ensure a comfortable ride. The driver will seek assistance from the car AI for this.",
    3: "The driver wants to dim the dashboard lights for better visibility at night. The driver will seek assistance from the car AI for this.",
    4: "The driver needs to fold the rearview mirrors for parking in a tight spot. The driver will seek assistance from the car AI for this.",
    5: "The driver wants to activate the lane-keeping assist feature to stay centered on the highway. The driver will seek assistance from the car AI for this.",
    6: "The driver wants to connect their phone via Bluetooth to play music through the car’s audio system. The driver will seek assistance from the car AI for this.",
    7: "The driver needs to adjust the seat position for better visibility while driving. The driver will seek assistance from the car AI for this.",
    8: "The driver wants to turn on the heated steering wheel for comfort in cold weather. The driver will seek assistance from the car AI for this.",
    9: "The driver wants to set the windshield wipers to automatic mode in response to incoming rain. The driver will seek assistance from the car AI for this.",
    10: "The driver needs to open the trunk remotely to load groceries. The driver will seek assistance from the car AI for this.",
    11: "The driver wants to change the driving mode from eco to sport for a more dynamic drive. The driver will seek assistance from the car AI for this.",
    12: "The driver wants to adjust the ambient lighting inside the car for a relaxing atmosphere. The driver will seek assistance from the car AI for this.",
    13: "The driver needs to lock the car doors before leaving the vehicle in a parking lot. The driver will seek assistance from the car AI for this.",
    14: "The driver wants to set a specific temperature for the passenger side of the climate control system. The driver will seek assistance from the car AI for this.",
    15: "The driver wants to activate the automatic high beams for better visibility on dark roads. The driver will seek assistance from the car AI for this.",
    16: "The driver needs to adjust the side mirrors to eliminate blind spots before starting the drive. The driver will seek assistance from the car AI for this.",
    17: "The driver wants to play a specific song from their playlist using voice commands. The driver will seek assistance from the car AI for this.",
    18: "The driver wants to disable the parking sensors while parallel parking to avoid constant alerts. The driver will seek assistance from the car AI for this.",
    19: "The driver needs to check the remaining fuel level before heading out on a long trip. The driver will seek assistance from the car AI for this.",
    20: "The driver wants to activate the defrost function to clear the windshield in cold weather. The driver will seek assistance from the car AI for this.",
    21: "The driver wants to adjust the seat lumbar support for enhanced comfort during a long drive. The driver will seek assistance from the car AI for this.",
    22: "The driver wants to set up navigation to avoid toll roads on the way to their destination. The driver will seek assistance from the car AI for this.",
    23: "The driver needs to enable the cruise control feature for a highway journey. The driver will seek assistance from the car AI for this.",
    24: "The driver wants to set the car’s interior temperature to a specific value using the climate control system. The driver will seek assistance from the car AI for this.",
    25: "The driver needs to activate the automatic emergency braking system for added safety. The driver will seek assistance from the car AI for this.",
    26: "The driver wants to set up their favorite radio station for a drive. The driver will seek assistance from the car AI for this.",
    27: "The driver wants to manually adjust the car’s headlights for improved visibility in foggy conditions. The driver will seek assistance from the car AI for this.",
    28: "The driver needs to fold the side mirrors in for a narrow garage. The driver will seek assistance from the car AI for this.",
    29: "The driver wants to turn on the rear window defroster to clear up foggy conditions. The driver will seek assistance from the car AI for this.",
    30: "The driver wants to adjust the car's seat position for a more comfortable driving posture. The driver will seek assistance from the car AI for this.",
    31: "The driver needs to set the car’s climate control to a specific temperature for a comfortable drive. The driver will seek assistance from the car AI for this.",
    32: "The driver wants to connect their phone to the car’s infotainment system via USB for charging. The driver will seek assistance from the car AI for this.",
    33: "The driver wants to check and adjust the car’s tire pressure before a long trip. The driver will seek assistance from the car AI for this.",
    34: "The driver wants to enable the car’s parking assist system to help with parallel parking. The driver will seek assistance from the car AI for this.",
    35: "The driver needs to turn on the car’s hazard lights in case of an emergency. The driver will seek assistance from the car AI for this.",
    36: "The driver wants to adjust the rearview mirror for a better view of the road behind. The driver will seek assistance from the car AI for this.",
    37: "The driver wants to set the seat position for the passenger for comfort. The driver will seek assistance from the car AI for this.",
    38: "The driver wants to activate the automatic parking feature for a parallel parking spot. The driver will seek assistance from the car AI for this.",
    39: "The driver needs to disable the automatic headlight system while driving through a tunnel. The driver will seek assistance from the car AI for this.",
    40: "The driver wants to change the infotainment display to show navigation information. The driver will seek assistance from the car AI for this.",
    41: "The driver needs to set the car’s heating system to warm up the cabin before starting the journey. The driver will seek assistance from the car AI for this.",
    42: "The driver wants to adjust the car’s seat memory settings for different drivers. The driver will seek assistance from the car AI for this.",
    43: "The driver wants to set up a hands-free phone call through the car’s infotainment system. The driver will seek assistance from the car AI for this.",
    44: "The driver needs to activate the rain-sensing wipers for light rain. The driver will seek assistance from the car AI for this.",
    45: "The driver wants to adjust the car’s suspension settings for a smoother ride. The driver will seek assistance from the car AI for this.",
    46: "The driver wants to open the sunroof for fresh air on a clear day. The driver will seek assistance from the car AI for this.",
    47: "The driver needs to set the car’s ventilation system to prevent the windshield from fogging up. The driver will seek assistance from the car AI for this.",
    48: "The driver wants to turn off the seatbelt reminder for the rear seats. The driver will seek assistance from the car AI for this.",
    49: "The driver wants to adjust the car’s throttle response for a more aggressive driving experience. The driver will seek assistance from the car AI for this.",
    50: "The driver needs to activate the car’s collision avoidance system for added safety. The driver will seek assistance from the car AI for this.",
    51: "The driver wants to set the climate control system to maintain a comfortable temperature during the drive. The driver will seek assistance from the car AI for this.",
    52: "The driver needs to change the car’s exterior lighting from bright to dim for better night driving. The driver will seek assistance from the car AI for this.",
    53: "The driver wants to check the current oil level and schedule an oil change if needed. The driver will seek assistance from the car AI for this.",
    54: "The driver needs to activate the adaptive cruise control for a more relaxed highway drive. The driver will seek assistance from the car AI for this.",
    55: "The driver wants to adjust the fan speed of the air conditioning system for optimal comfort. The driver will seek assistance from the car AI for this.",
    56: "The driver needs to set the car’s navigation system to avoid traffic jams. The driver will seek assistance from the car AI for this.",
    57: "The driver wants to activate the automatic door locking feature when the car starts moving. The driver will seek assistance from the car AI for this.",
    58: "The driver wants to enable the car’s blind-spot monitoring system for safer lane changes. The driver will seek assistance from the car AI for this.",
    59: "The driver needs to adjust the rear window tinting for privacy and reduced glare. The driver will seek assistance from the car AI for this.",
    60: "The driver wants to set the car’s temperature control to cool down the cabin quickly. The driver will seek assistance from the car AI for this.",
    61: "The driver wants to change the car’s driving mode to ‘Comfort’ for a smoother ride on rough roads. The driver will seek assistance from the car AI for this.",
    62: "The driver needs to activate the car’s automatic parking brake before shifting into drive. The driver will seek assistance from the car AI for this.",
    63: "The driver wants to set up a specific driver profile with personalized settings. The driver will seek assistance from the car AI for this.",
    64: "The driver needs to adjust the car’s steering wheel angle for better driving comfort. The driver will seek assistance from the car AI for this.",
    65: "The driver wants to activate the car’s lane departure warning system for safer highway driving. The driver will seek assistance from the car AI for this.",
    66: "The driver needs to connect their phone to the car’s infotainment system for hands-free calls. The driver will seek assistance from the car AI for this.",
    67: "The driver wants to adjust the seat height to improve their driving posture. The driver will seek assistance from the car AI for this.",
    68: "The driver wants to enable the car’s parking assist system for parallel parking. The driver will seek assistance from the car AI for this.",
    69: "The driver needs to turn on the car’s rearview camera for better visibility while reversing. The driver will seek assistance from the car AI for this.",
    70: "The driver wants to set the car’s navigation system to avoid specific routes. The driver will seek assistance from the car AI for this.",
    71: "The driver wants to activate the car’s traffic sign recognition system for added safety. The driver will seek assistance from the car AI for this.",
    72: "The driver needs to adjust the car’s climate control settings to account for a change in weather. The driver will seek assistance from the car AI for this.",
    73: "The driver wants to open the rear windows slightly for ventilation. The driver will seek assistance from the car AI for this.",
    74: "The driver wants to set the car’s driving mode to ‘Eco’ to maximize fuel efficiency. The driver will seek assistance from the car AI for this.",
    75: "The driver needs to turn off the car’s collision warning system for off-road driving. The driver will seek assistance from the car AI for this.",
    76: "The driver wants to set up the car’s voice control system for hands-free operation. The driver will seek assistance from the car AI for this.",
    77: "The driver needs to adjust the car’s seat position for a more ergonomic driving experience. The driver will seek assistance from the car AI for this.",
    78: "The driver wants to activate the car’s automatic headlight adjustment for varying light conditions. The driver will seek assistance from the car AI for this.",
    79: "The driver needs to check and adjust the car’s fluid levels before a long journey. The driver will seek assistance from the car AI for this.",
    80: "The driver wants to set the car’s audio system to play a podcast during the drive. The driver will seek assistance from the car AI for this.",
    81: "The driver wants to activate the car’s emergency call system in case of an accident. The driver will seek assistance from the car AI for this.",
    82: "The driver needs to adjust the car’s mirror settings to reduce glare from headlights behind. The driver will seek assistance from the car AI for this.",
    83: "The driver wants to set up the car’s interior lighting for a special occasion. The driver will seek assistance from the car AI for this.",
    84: "The driver needs to activate the car’s side airbags for enhanced safety. The driver will seek assistance from the car AI for this.",
    85: "The driver wants to adjust the car’s seat position for a passenger who is shorter. The driver will seek assistance from the car AI for this.",
    86: "The driver wants to set the car’s climate control to maintain a specific temperature while driving through varying weather conditions. The driver will seek assistance from the car AI for this.",
    87: "The driver needs to activate the car’s lane assist feature to help with lane changes. The driver will seek assistance from the car AI for this.",
    88: "The driver wants to check the current traffic conditions and find the best route to their destination. The driver will seek assistance from the car AI for this.",
    89: "The driver needs to adjust the car’s window tint to reduce glare from the sun. The driver will seek assistance from the car AI for this.",
    90: "The driver wants to set the car’s interior temperature to a comfortable level for the passengers. The driver will seek assistance from the car AI for this.",
    91: "The driver wants to activate the car’s parking sensors to assist with parking in a tight spot. The driver will seek assistance from the car AI for this.",
    92: "The driver needs to adjust the car’s seat recline for a more relaxed driving position. The driver will seek assistance from the car AI for this.",
    93: "The driver wants to set up the car’s navigation to show points of interest along the route. The driver will seek assistance from the car AI for this.",
    94: "The driver needs to activate the car’s blind-spot detection system for safer lane changes. The driver will seek assistance from the car AI for this.",
    95: "The driver wants to adjust the car’s climate control to improve airflow and comfort. The driver will seek assistance from the car AI for this.",
    96: "The driver wants to set the car’s infotainment system to display the weather forecast for the day. The driver will seek assistance from the car AI for this.",
    97: "The driver needs to activate the car’s automatic parking system for a parallel parking space. The driver will seek assistance from the car AI for this.",
    98: "The driver wants to adjust the car’s suspension settings for off-road driving. The driver will seek assistance from the car AI for this.",
    99: "The driver needs to set the car’s infotainment system to play a specific genre of music. The driver will seek assistance from the car AI for this.",
    100: "The driver wants to activate the car’s traction control system for better handling in slippery conditions. The driver will seek assistance from the car AI for this."
}
