contexts = {
    1: "The driver wants to check the tire pressure before starting a trip from Mumbai to Surat. The driver will seek assistance from the car AI for this.",
    2: "The driver requests a status update on the car's battery health before heading out on a long journey from Chennai to Tirupati. The driver will seek assistance from the car AI for this.",
    3: "The driver asks the car AI to monitor brake performance during a drive through the Western Ghats. The driver will seek assistance from the car AI for this.",
    4: "The driver requests a diagnostic scan of the vehicle after hitting a pothole on the way to Delhi. The driver will seek assistance from the car AI for this.",
    5: "The driver needs to locate the nearest service center for a quick vehicle inspection while driving through Bangalore. The driver will seek assistance from the car AI for this.",
    6: "The driver wants to find out the status of the air filter before a long trip from Kolkata to Bhubaneswar. The driver will seek assistance from the car AI for this.",
    7: "The driver asks the car AI for recommendations on tire maintenance during a long drive to Rishikesh. The driver will seek assistance from the car AI for this.",
    8: "The driver wants to check engine performance after noticing unusual sounds while driving to Hyderabad. The driver will seek assistance from the car AI for this.",
    9: "The driver requests a status update on the car’s electrical systems before heading out on a long drive from Pune to Nashik. The driver will seek assistance from the car AI for this.",
    10: "The driver wants to know the brake performance details before descending a steep road in Shimla. The driver will seek assistance from the car AI for this.",
    11: "The driver needs to check oil levels before starting a long drive across the Thar Desert. The driver will seek assistance from the car AI for this.",
    12: "The driver requests a diagnostic check on the car’s air conditioning system while driving through the hot plains of Rajasthan. The driver will seek assistance from the car AI for this.",
    13: "The driver wants to inspect the suspension system after driving over a rough road in the Himalayas. The driver will seek assistance from the car AI for this.",
    14: "The driver asks the car AI to check for any fluid leaks before traveling from Mumbai to Goa. The driver will seek assistance from the car AI for this.",
    15: "The driver wants to schedule a tire rotation before a cross-country drive from Delhi to Mumbai. The driver will seek assistance from the car AI for this.",
    16: "The driver requests a diagnostic scan of the engine after a warning light turns on during a drive through the Konkan Coast. The driver will seek assistance from the car AI for this.",
    17: "The driver wants to check brake pad wear before descending a mountain pass in Himachal Pradesh. The driver will seek assistance from the car AI for this.",
    18: "The driver asks the car AI for a report on battery health during a drive in the chilly areas of Ladakh. The driver will seek assistance from the car AI for this.",
    19: "The driver needs to find a nearby mechanic after noticing a strange noise coming from the engine while in a remote village in Uttarakhand. The driver will seek assistance from the car AI for this.",
    20: "The driver wants to check the fluid levels before embarking on a long journey through the forests of Kerala. The driver will seek assistance from the car AI for this.",
    21: "The driver requests a status update on the car’s transmission system while traveling on a highway from Chennai to Bengaluru. The driver will seek assistance from the car AI for this.",
    22: "The driver needs to perform a routine check on the car’s radiator temperature while driving through the desert in Gujarat. The driver will seek assistance from the car AI for this.",
    23: "The driver wants to verify tire tread depth before going on a road trip across the coastal regions of Andhra Pradesh. The driver will seek assistance from the car AI for this.",
    24: "The driver requests an oil change reminder while navigating through the busy streets of Mumbai. The driver will seek assistance from the car AI for this.",
    25: "The driver needs to inspect the engine belts after a sudden loss of power on a remote road in Arunachal Pradesh. The driver will seek assistance from the car AI for this.",
    26: "The driver wants to check if the car’s catalytic converter is functioning properly before a long trip from Jaipur to Agra. The driver will seek assistance from the car AI for this.",
    27: "The driver asks the car AI to monitor the car’s fuel efficiency while driving in the hills of Sikkim. The driver will seek assistance from the car AI for this.",
    28: "The driver wants to get a status update on the car’s steering system before heading out on a road trip to Pondicherry. The driver will seek assistance from the car AI for this.",
    29: "The driver needs to check the status of the car’s exhaust system after experiencing decreased acceleration in the hills of Meghalaya. The driver will seek assistance from the car AI for this.",
    30: "The driver requests a diagnostic check on the car’s heating system while driving through the snowy roads of Shimla. The driver will seek assistance from the car AI for this.",
    31: "The driver wants to verify that the car’s brake fluid is at an adequate level before starting a trip through the Western Ghats. The driver will seek assistance from the car AI for this.",
    32: "The driver asks the car AI to perform a diagnostic check after a sudden drop in engine power during a drive in the Nilgiri Hills. The driver will seek assistance from the car AI for this.",
    33: "The driver needs to schedule a cabin air filter replacement before embarking on a journey through the dense forests of Madhya Pradesh. The driver will seek assistance from the car AI for this.",
    34: "The driver wants to check for any issues with the car’s turbocharger before heading out on a road trip to Pune. The driver will seek assistance from the car AI for this.",
    35: "The driver requests a diagnostic check on the car’s ABS system while driving through the busy roads of Bangalore. The driver will seek assistance from the car AI for this.",
    36: "The driver wants to know the condition of the car’s alternator before a long drive through the coastal roads of Kerala. The driver will seek assistance from the car AI for this.",
    37: "The driver needs to perform a coolant level check before starting a trip through the deserts of Rajasthan. The driver will seek assistance from the car AI for this.",
    38: "The driver asks the car AI to monitor the car’s transmission temperature during a drive through the heat of Gujarat. The driver will seek assistance from the car AI for this.",
    39: "The driver wants to perform a check on the car’s differential system after a sudden jolt while driving on an uneven road in Uttarakhand. The driver will seek assistance from the car AI for this.",
    40: "The driver needs to inspect the car’s fuel filter before embarking on a road trip across the plains of Uttar Pradesh. The driver will seek assistance from the car AI for this.",
    41: "The driver wants to schedule a brake inspection before starting a long drive through the mountainous roads of Himachal Pradesh. The driver will seek assistance from the car AI for this.",
    42: "The driver requests a diagnostic check on the car’s fuel injection system while driving through the highways of Maharashtra. The driver will seek assistance from the car AI for this.",
    43: "The driver wants to check the condition of the car’s spark plugs before heading out on a trip to the hills of Arunachal Pradesh. The driver will seek assistance from the car AI for this.",
    44: "The driver asks the car AI to perform a check on the car’s power steering fluid levels while driving through the bustling streets of Delhi. The driver will seek assistance from the car AI for this.",
    45: "The driver wants to verify the car’s emission levels before starting a journey through the plains of Punjab. The driver will seek assistance from the car AI for this.",
    46: "The driver requests a diagnostic scan of the car’s charging system during a drive through the cold regions of Kashmir. The driver will seek assistance from the car AI for this.",
    47: "The driver needs to perform a tire alignment check before a long drive across the flat terrains of Haryana. The driver will seek assistance from the car AI for this.",
    48: "The driver wants to check the condition of the car’s transmission belts after experiencing slipping while driving in the hot weather of Gujarat. The driver will seek assistance from the car AI for this.",
    49: "The driver asks the car AI to monitor engine performance during a trip through the hills of Himachal Pradesh. The driver will seek assistance from the car AI for this.",
    50: "The driver wants to schedule a car battery inspection before starting a journey through the remote areas of Chhattisgarh. The driver will seek assistance from the car AI for this.",
    51: "The driver requests a diagnostic check on the car’s turbo boost levels while driving through the high altitudes of Sikkim. The driver will seek assistance from the car AI for this.",
    52: "The driver needs to check the car’s brake fluid levels before heading out on a long drive through the plains of Bihar. The driver will seek assistance from the car AI for this.",
    53: "The driver wants to inspect the car’s clutch system before a road trip through the dense forests of Kerala. The driver will seek assistance from the car AI for this.",
    54: "The driver asks the car AI to perform a check on the car’s suspension system while driving on a rugged road in Uttarakhand. The driver will seek assistance from the car AI for this.",
    55: "The driver wants to check the condition of the car’s spark plugs before starting a drive through the coastal roads of Tamil Nadu. The driver will seek assistance from the car AI for this.",
    56: "The driver requests a status update on the car’s electrical system before a long journey through the hilly terrains of Meghalaya. The driver will seek assistance from the car AI for this.",
    57: "The driver needs to inspect the car’s battery terminals after experiencing electrical issues while driving in the hot weather of Rajasthan. The driver will seek assistance from the car AI for this.",
    58: "The driver wants to check the air conditioning system before embarking on a road trip through the humid regions of Kerala. The driver will seek assistance from the car AI for this.",
    59: "The driver asks the car AI to perform a diagnostic scan on the vehicle’s cooling system during a drive through the desert in Gujarat. The driver will seek assistance from the car AI for this.",
    60: "The driver wants to verify the car’s alignment before starting a journey through the busy roads of Chennai. The driver will seek assistance from the car AI for this.",
    61: "The driver requests a check on the car’s brake system before driving through the steep inclines of Shimla. The driver will seek assistance from the car AI for this.",
    62: "The driver needs to inspect the car’s transmission fluid levels before heading out on a road trip through the remote areas of Arunachal Pradesh. The driver will seek assistance from the car AI for this.",
    63: "The driver wants to get a diagnostic check on the vehicle’s fuel system after experiencing reduced mileage during a drive in Uttar Pradesh. The driver will seek assistance from the car AI for this.",
    64: "The driver asks the car AI to perform a check on the car’s drive belts while driving through the hilly terrain of Meghalaya. The driver will seek assistance from the car AI for this.",
    65: "The driver wants to check the status of the car’s differential system before starting a journey through the remote areas of Rajasthan. The driver will seek assistance from the car AI for this.",
    66: "The driver requests a diagnostic scan on the car’s engine temperature while driving through the cold regions of Himachal Pradesh. The driver will seek assistance from the car AI for this.",
    67: "The driver needs to inspect the car’s wheel alignment before heading out on a long drive across the flat roads of Punjab. The driver will seek assistance from the car AI for this.",
    68: "The driver wants to check the air filter condition before starting a trip through the dusty roads of Rajasthan. The driver will seek assistance from the car AI for this.",
    69: "The driver asks the car AI to perform a diagnostic check on the car’s transmission system while driving in the hot weather of Gujarat. The driver will seek assistance from the car AI for this.",
    70: "The driver wants to check the status of the car’s oil filter before a road trip through the remote areas of Arunachal Pradesh. The driver will seek assistance from the car AI for this.",
    71: "The driver requests a status update on the car’s ignition system before heading out on a long drive through the plains of Haryana. The driver will seek assistance from the car AI for this.",
    72: "The driver needs to perform a check on the car’s shock absorbers before starting a journey through the rugged roads of Uttarakhand. The driver will seek assistance from the car AI for this.",
    73: "The driver wants to inspect the car’s fuel pump before embarking on a long drive through the forests of Madhya Pradesh. The driver will seek assistance from the car AI for this.",
    74: "The driver asks the car AI to check the status of the car’s exhaust system while driving through the cold regions of Kashmir. The driver will seek assistance from the car AI for this.",
    75: "The driver wants to schedule a service for the car’s power windows system before starting a road trip through the dense forests of Kerala. The driver will seek assistance from the car AI for this.",
    76: "The driver requests a diagnostic check on the car’s intake manifold before heading out on a drive through the coastal roads of Tamil Nadu. The driver will seek assistance from the car AI for this.",
    77: "The driver needs to inspect the car’s wheel bearings after noticing a strange noise during a drive through the Western Ghats. The driver will seek assistance from the car AI for this.",
    78: "The driver wants to check the condition of the car’s fuel lines before a long journey through the hot plains of Rajasthan. The driver will seek assistance from the car AI for this.",
    79: "The driver asks the car AI to perform a diagnostic scan on the car’s turbocharger while driving through the high altitudes of Sikkim. The driver will seek assistance from the car AI for this.",
    80: "The driver wants to verify the status of the car’s powertrain before starting a trip through the remote areas of Chhattisgarh. The driver will seek assistance from the car AI for this.",
    81: "The driver requests a diagnostic check on the car’s fuel tank after experiencing fluctuating fuel levels while driving in the dense forests of Madhya Pradesh. The driver will seek assistance from the car AI for this.",
    82: "The driver needs to perform a check on the car’s exhaust manifold before embarking on a journey through the hilly regions of Himachal Pradesh. The driver will seek assistance from the car AI for this.",
    83: "The driver wants to inspect the car’s brake rotors before starting a drive through the steep hills of Shimla. The driver will seek assistance from the car AI for this.",
    84: "The driver asks the car AI to check the condition of the car’s air compressor while driving through the hot weather of Gujarat. The driver will seek assistance from the car AI for this.",
    85: "The driver wants to get a diagnostic scan on the car’s battery charging system before heading out on a trip through the coastal roads of Tamil Nadu. The driver will seek assistance from the car AI for this.",
    86: "The driver requests a status update on the car’s engine oil before starting a journey through the rural roads of Karnataka. The driver will seek assistance from the car AI for this.",
    87: "The driver needs to check the car’s power steering system after experiencing difficulty steering during a drive in the busy streets of Delhi. The driver will seek assistance from the car AI for this.",
    88: "The driver wants to inspect the car’s fuel injectors before a road trip through the hills of Meghalaya. The driver will seek assistance from the car AI for this.",
    89: "The driver asks the car AI to perform a diagnostic check on the vehicle’s climate control system while driving through the chilly regions of Ladakh. The driver will seek assistance from the car AI for this.",
    90: "The driver wants to check the condition of the car’s timing belt before starting a journey through the dusty roads of Rajasthan. The driver will seek assistance from the car AI for this.",
    91: "The driver requests a check on the car’s differential fluid levels while driving through the rugged terrain of Arunachal Pradesh. The driver will seek assistance from the car AI for this.",
    92: "The driver needs to inspect the car’s turbocharger boost levels before heading out on a drive through the remote areas of Chhattisgarh. The driver will seek assistance from the car AI for this.",
    93: "The driver wants to verify the status of the car’s radiator before starting a long drive through the hot plains of Gujarat. The driver will seek assistance from the car AI for this.",
    94: "The driver asks the car AI to perform a diagnostic scan on the vehicle’s suspension system while driving through the uneven roads of Himachal Pradesh. The driver will seek assistance from the car AI for this.",
    95: "The driver wants to check the condition of the car’s brake calipers before embarking on a road trip through the hills of Meghalaya. The driver will seek assistance from the car AI for this.",
    96: "The driver requests a diagnostic check on the car’s drive shafts before starting a journey through the rough roads of Uttarakhand. The driver will seek assistance from the car AI for this.",
    97: "The driver needs to inspect the car’s engine mounts after noticing vibrations during a drive through the hot weather of Rajasthan. The driver will seek assistance from the car AI for this.",
    98: "The driver wants to check the car’s oil levels before starting a road trip through the remote areas of Arunachal Pradesh. The driver will seek assistance from the car AI for this.",
    99: "The driver asks the car AI to perform a diagnostic check on the car’s brake lines while driving through the hilly regions of Himachal Pradesh. The driver will seek assistance from the car AI for this.",
    100: "The driver wants to run a diagnostic check on the transmission fluid levels before a long road trip to Rajasthan. The driver will seek assistance from the car AI for this."
}
