contexts = {
    1: "The driver wants to request a curated music playlist for a road trip from Mumbai to Lonavala. The driver will seek assistance from the car AI for this.",
    2: "The driver wants to listen to a local radio station while driving through Chennai. The driver will seek assistance from the car AI for this.",
    3: "The driver is looking for recommendations for an audiobook during a solo trip from Delhi to Jaipur. The driver will seek assistance from the car AI for this.",
    4: "The driver wants to stream the latest Bollywood hits on a drive from Bangalore to Mysore. The driver will seek assistance from the car AI for this.",
    5: "The driver wants to listen to a podcast about technology during a long drive from Pune to Hyderabad. The driver will seek assistance from the car AI for this.",
    6: "The driver wants to catch up on the latest sports news while driving from Ahmedabad to Surat. The driver will seek assistance from the car AI for this.",
    7: "The driver wants to play a trivia game to pass time during a commute from Noida to Gurgaon. The driver will seek assistance from the car AI for this.",
    8: "The driver is interested in listening to a historical fiction audiobook during a trip from Kolkata to Bhubaneswar. The driver will seek assistance from the car AI for this.",
    9: "The driver wants to listen to calming instrumental music while traveling through the scenic routes of Shimla. The driver will seek assistance from the car AI for this.",
    10: "The driver wants to play a popular podcast series about true crime while driving from Jaipur to Agra. The driver will seek assistance from the car AI for this.",
    11: "The driver wants to watch a family-friendly movie while parked at a rest stop on a road trip from Mumbai to Goa. The driver will seek assistance from the car AI for this.",
    12: "The driver wants to listen to the latest updates on global politics during a long drive from Delhi to Amritsar. The driver will seek assistance from the car AI for this.",
    13: "The driver is looking for an upbeat workout playlist for a drive to the gym in Bangalore. The driver will seek assistance from the car AI for this.",
    14: "The driver wants to listen to a daily news roundup while traveling through the city of Hyderabad. The driver will seek assistance from the car AI for this.",
    15: "The driver wants to stream a comedy podcast to lighten the mood during a lengthy trip from Kolkata to Varanasi. The driver will seek assistance from the car AI for this.",
    16: "The driver wants to request a playlist of classic rock songs for a drive through the countryside of Rajasthan. The driver will seek assistance from the car AI for this.",
    17: "The driver is interested in listening to a motivational audiobook while heading to a business meeting in Chennai. The driver will seek assistance from the car AI for this.",
    18: "The driver wants to play an engaging science fiction audiobook on a road trip from Delhi to Shimla. The driver will seek assistance from the car AI for this.",
    19: "The driver wants to listen to relaxing ambient sounds during a drive from Pune to Mumbai. The driver will seek assistance from the car AI for this.",
    20: "The driver is interested in streaming a documentary about wildlife while traveling through the forests of Kerala. The driver will seek assistance from the car AI for this.",
    21: "The driver wants to catch up on the latest entertainment news during a drive from Bangalore to Chennai. The driver will seek assistance from the car AI for this.",
    22: "The driver wants to play a light-hearted podcast about travel tips while heading to the beach in Goa. The driver will seek assistance from the car AI for this.",
    23: "The driver wants to request a playlist of jazz standards for a leisurely drive through the wine country of Nashik. The driver will seek assistance from the car AI for this.",
    24: "The driver wants to listen to a news podcast about tech innovations while commuting from Pune to Mumbai. The driver will seek assistance from the car AI for this.",
    25: "The driver wants to stream a romantic movie while parked at a scenic overlook on a trip from Delhi to Shimla. The driver will seek assistance from the car AI for this.",
    26: "The driver is interested in listening to a fantasy audiobook while traveling through the mountains of Himachal Pradesh. The driver will seek assistance from the car AI for this.",
    27: "The driver wants to catch up on world news updates during a road trip from Ahmedabad to Udaipur. The driver will seek assistance from the car AI for this.",
    28: "The driver wants to request a mix of recent pop hits while driving from Gurgaon to Delhi. The driver will seek assistance from the car AI for this.",
    29: "The driver wants to play a popular science podcast while traveling through the rural areas of Punjab. The driver will seek assistance from the car AI for this.",
    30: "The driver wants to listen to an audio guide about local attractions while driving through the historic streets of Jaipur. The driver will seek assistance from the car AI for this.",
    31: "The driver wants to stream a curated list of indie music while on a road trip from Mumbai to Pune. The driver will seek assistance from the car AI for this.",
    32: "The driver wants to listen to a motivational speaker during a long drive from Delhi to Haridwar. The driver will seek assistance from the car AI for this.",
    33: "The driver is looking for an educational podcast about space exploration while driving from Bangalore to Mysore. The driver will seek assistance from the car AI for this.",
    34: "The driver wants to request a playlist of 80s music hits for a nostalgic drive through the city of Mumbai. The driver will seek assistance from the car AI for this.",
    35: "The driver wants to listen to an audiobook about business strategy while commuting from Noida to Delhi. The driver will seek assistance from the car AI for this.",
    36: "The driver wants to stream a documentary about historical landmarks while traveling through the state of Tamil Nadu. The driver will seek assistance from the car AI for this.",
    37: "The driver wants to play a fun trivia game to keep entertained during a road trip from Hyderabad to Bangalore. The driver will seek assistance from the car AI for this.",
    38: "The driver wants to catch up on the latest music industry gossip while driving through the streets of Chennai. The driver will seek assistance from the car AI for this.",
    39: "The driver wants to listen to a suspenseful crime thriller audiobook during a solo drive from Mumbai to Ahmedabad. The driver will seek assistance from the car AI for this.",
    40: "The driver wants to stream a playlist of relaxing beach tunes while heading to a vacation spot in Goa. The driver will seek assistance from the car AI for this.",
    41: "The driver wants to listen to an engaging podcast about true crime while driving from Delhi to Jaipur. The driver will seek assistance from the car AI for this.",
    42: "The driver wants to request a playlist of classical music for a calm drive through the hills of Shimla. The driver will seek assistance from the car AI for this.",
    43: "The driver wants to catch up on the latest tech news during a drive from Pune to Mumbai. The driver will seek assistance from the car AI for this.",
    44: "The driver wants to listen to a motivational podcast while heading to a remote retreat in Uttarakhand. The driver will seek assistance from the car AI for this.",
    45: "The driver wants to play a popular comedy series during a leisurely drive from Bangalore to Chennai. The driver will seek assistance from the car AI for this.",
    46: "The driver wants to stream an audio guide about local cuisine while traveling through the food streets of Delhi. The driver will seek assistance from the car AI for this.",
    47: "The driver wants to listen to a dramatic thriller audiobook during a long trip from Kolkata to Bhubaneswar. The driver will seek assistance from the car AI for this.",
    48: "The driver wants to request a playlist of energetic rock music for a drive to a music festival in Pune. The driver will seek assistance from the car AI for this.",
    49: "The driver wants to catch up on the latest celebrity news during a drive from Mumbai to Goa. The driver will seek assistance from the car AI for this.",
    50: "The driver wants to listen to a relaxing nature sounds playlist during a scenic drive through Kerala. The driver will seek assistance from the car AI for this.",
    51: "The driver wants to stream a classic movie while parked at a scenic spot during a road trip from Delhi to Shimla. The driver will seek assistance from the car AI for this.",
    52: "The driver wants to listen to a podcast about personal finance while driving from Bangalore to Mysore. The driver will seek assistance from the car AI for this.",
    53: "The driver wants to request a playlist of indie pop songs for a drive through the coastal roads of Goa. The driver will seek assistance from the car AI for this.",
    54: "The driver wants to play a fantasy audiobook during a road trip from Mumbai to Jaipur. The driver will seek assistance from the car AI for this.",
    55: "The driver wants to listen to an audio guide about famous landmarks while traveling through the historic region of Rajasthan. The driver will seek assistance from the car AI for this.",
    56: "The driver wants to catch up on the latest environmental news during a drive from Pune to Nashik. The driver will seek assistance from the car AI for this.",
    57: "The driver wants to request a playlist of upbeat dance tracks for a drive to a party in Chennai. The driver will seek assistance from the car AI for this.",
    58: "The driver wants to listen to a historical documentary podcast while traveling through the cultural heritage sites of Delhi. The driver will seek assistance from the car AI for this.",
    59: "The driver wants to stream a playlist of soothing instrumental music during a peaceful drive through the countryside of Himachal Pradesh. The driver will seek assistance from the car AI for this.",
    60: "The driver wants to play a popular motivational audiobook while heading to a conference in Bangalore. The driver will seek assistance from the car AI for this.",
    61: "The driver wants to listen to a daily news briefing during a commute from Gurgaon to Delhi. The driver will seek assistance from the car AI for this.",
    62: "The driver wants to request a playlist of vintage jazz recordings for a drive through the city of Kolkata. The driver will seek assistance from the car AI for this.",
    63: "The driver wants to play a comedy podcast series during a long drive from Hyderabad to Bangalore. The driver will seek assistance from the car AI for this.",
    64: "The driver wants to catch up on the latest business news while traveling from Mumbai to Pune. The driver will seek assistance from the car AI for this.",
    65: "The driver wants to listen to a motivational podcast while driving to a marathon in Delhi. The driver will seek assistance from the car AI for this.",
    66: "The driver wants to stream an action movie while parked at a rest stop on a trip from Chennai to Bangalore. The driver will seek assistance from the car AI for this.",
    67: "The driver wants to request a playlist of electronic dance music for a drive to a nightclub in Mumbai. The driver will seek assistance from the car AI for this.",
    68: "The driver wants to listen to an educational podcast about economics during a drive from Pune to Goa. The driver will seek assistance from the car AI for this.",
    69: "The driver wants to play an engaging podcast about personal development while heading to a retreat in Kerala. The driver will seek assistance from the car AI for this.",
    70: "The driver wants to catch up on the latest fashion news during a drive through the streets of Delhi. The driver will seek assistance from the car AI for this.",
    71: "The driver wants to listen to a curated playlist of world music during a road trip from Bangalore to Mysore. The driver will seek assistance from the car AI for this.",
    72: "The driver wants to play a popular novel audiobook during a long journey from Mumbai to Goa. The driver will seek assistance from the car AI for this.",
    73: "The driver wants to stream a podcast series about startups while driving from Hyderabad to Bangalore. The driver will seek assistance from the car AI for this.",
    74: "The driver wants to listen to a relaxing classical music playlist while driving through the scenic routes of Himachal Pradesh. The driver will seek assistance from the car AI for this.",
    75: "The driver wants to request a playlist of romantic songs for a drive to a date night in Chennai. The driver will seek assistance from the car AI for this.",
    76: "The driver wants to listen to a podcast about global cultures while traveling from Delhi to Mumbai. The driver will seek assistance from the car AI for this.",
    77: "The driver wants to stream a documentary about ancient civilizations during a road trip from Kolkata to Varanasi. The driver will seek assistance from the car AI for this.",
    78: "The driver wants to catch up on the latest tech reviews while driving from Bangalore to Chennai. The driver will seek assistance from the car AI for this.",
    79: "The driver wants to listen to a thriller audiobook during a solo trip from Delhi to Jaipur. The driver will seek assistance from the car AI for this.",
    80: "The driver wants to play a light-hearted podcast about hobbies while driving through the city of Hyderabad. The driver will seek assistance from the car AI for this.",
    81: "The driver wants to request a playlist of country music hits for a drive through the rural areas of Punjab. The driver will seek assistance from the car AI for this.",
    82: "The driver wants to stream a playlist of high-energy pop songs for a road trip to a music festival in Goa. The driver will seek assistance from the car AI for this.",
    83: "The driver wants to listen to a podcast about mindfulness during a drive from Mumbai to Pune. The driver will seek assistance from the car AI for this.",
    84: "The driver wants to catch up on the latest business trends while driving from Bangalore to Mysore. The driver will seek assistance from the car AI for this.",
    85: "The driver wants to listen to a fantasy novel audiobook during a drive through the scenic routes of Kerala. The driver will seek assistance from the car AI for this.",
    86: "The driver wants to stream a playlist of motivational speeches while heading to a motivational seminar in Chennai. The driver will seek assistance from the car AI for this.",
    87: "The driver wants to play a podcast about travel adventures while on a road trip from Delhi to Shimla. The driver will seek assistance from the car AI for this.",
    88: "The driver wants to request a playlist of popular music from the 90s while driving through the streets of Kolkata. The driver will seek assistance from the car AI for this.",
    89: "The driver wants to listen to an engaging sci-fi audiobook during a long drive from Mumbai to Goa. The driver will seek assistance from the car AI for this.",
    90: "The driver wants to stream a motivational podcast series while driving to a corporate retreat in Bangalore. The driver will seek assistance from the car AI for this.",
    91: "The driver wants to catch up on the latest news about scientific discoveries during a drive from Delhi to Agra. The driver will seek assistance from the car AI for this.",
    92: "The driver wants to listen to a relaxing playlist of smooth jazz while driving through the countryside of Tamil Nadu. The driver will seek assistance from the car AI for this.",
    93: "The driver wants to stream a podcast about wellness and self-care while driving from Hyderabad to Bangalore. The driver will seek assistance from the car AI for this.",
    94: "The driver wants to play a trivia game about movies while traveling from Chennai to Bangalore. The driver will seek assistance from the car AI for this.",
    95: "The driver wants to request a playlist of high-tempo electronic music for a drive to a tech conference in Mumbai. The driver will seek assistance from the car AI for this.",
    96: "The driver wants to listen to a daily podcast about world affairs while commuting from Noida to Delhi. The driver will seek assistance from the car AI for this.",
    97: "The driver wants to catch up on the latest updates in the fashion industry while driving through the streets of Mumbai. The driver will seek assistance from the car AI for this.",
    98: "The driver wants to play a gripping detective audiobook during a drive from Jaipur to Agra. The driver will seek assistance from the car AI for this.",
    99: "The driver wants to listen to a podcast about global travel destinations while heading to a vacation spot in Goa. The driver will seek assistance from the car AI for this.",
    100: "The driver wants to stream a playlist of motivational songs while driving to a marathon in Chennai. The driver will seek assistance from the car AI for this."
}
