contexts = {
    1: "The driver wants to find the best street food on the route while driving from Kolkata to Delhi. The driver will seek assistance from the car AI for this.",
    2: "The driver requests recommendations for top-rated restaurants along the way during a trip from Mumbai to Goa. The driver will seek assistance from the car AI for this.",
    3: "The driver is asking for suggestions for the best coffee shops in Bangalore and nearby locations on the route to Chennai. The driver will seek assistance from the car AI for this.",
    4: "The driver wants to plan a one-week road trip across Rajasthan, visiting major cities like Jaipur, Jodhpur, and Udaipur, and wants to include local attractions on the route. The driver will seek assistance from the car AI for this.",
    5: "The driver requests a day-by-day travel itinerary for a road trip from Delhi to Amritsar, including rest stops, local attractions, and dining options along the way. The driver will seek assistance from the car AI for this.",
    6: "The driver wants to find popular hill stations near Bangalore and interesting spots along the drive to Coorg. The driver will seek assistance from the car AI for this.",
    7: "The driver asks for suggestions for spiritual destinations near Varanasi and activities on the route to these destinations. The driver will seek assistance from the car AI for this.",
    8: "The driver is inquiring about potential road closures or construction on the way from Chennai to Pondicherry, and nearby attractions or dining options. The driver will seek assistance from the car AI for this.",
    9: "The driver requests recommendations for local markets and shopping spots both in Jaipur and along the route. The driver will seek assistance from the car AI for this.",
    10: "The driver wants to find pet-friendly hotels on the way to Coorg and nearby attractions along the route. The driver will seek assistance from the car AI for this.",
    11: "The driver seeks dining options for vegetarian food while traveling from Ahmedabad to Surat. The driver will seek assistance from the car AI for this.",
    12: "The driver needs recommendations for family-friendly activities along the route from Delhi to Shimla. The driver will seek assistance from the car AI for this.",
    13: "The driver is looking for scenic viewpoints and local attractions while driving from Mumbai to Pune. The driver will seek assistance from the car AI for this.",
    14: "The driver requests suggestions for cozy cafes in the vicinity of Kolkata and along the drive to Darjeeling. The driver will seek assistance from the car AI for this.",
    15: "The driver wants to explore historical sites and local eateries during a road trip from Hyderabad to Bangalore. The driver will seek assistance from the car AI for this.",
    16: "The driver seeks recommendations for the best hiking trails and outdoor activities around Munnar while driving from Cochin. The driver will seek assistance from the car AI for this.",
    17: "The driver wants to find local entertainment options such as theaters and music venues in the area of Chennai and along the route to Madurai. The driver will seek assistance from the car AI for this.",
    18: "The driver requests a list of top-rated hotels and unique attractions for a visit to the beaches of Goa and the drive from Mumbai. The driver will seek assistance from the car AI for this.",
    19: "The driver is planning a trip from Pune to Nashik and needs suggestions for local wineries and food stops along the way. The driver will seek assistance from the car AI for this.",
    20: "The driver seeks recommendations for cultural festivals and local events during a drive from Delhi to Jaipur. The driver will seek assistance from the car AI for this.",
    21: "The driver wants to explore the local art scene and find galleries while traveling from Bangalore to Hyderabad. The driver will seek assistance from the car AI for this.",
    22: "The driver is interested in discovering unique local experiences and hidden gems around the suburbs of Mumbai during a road trip to Gujarat. The driver will seek assistance from the car AI for this.",
    23: "The driver requests suggestions for relaxing spas and wellness centers along the route from Bangalore to Coorg. The driver will seek assistance from the car AI for this.",
    24: "The driver seeks to find top-rated seafood restaurants in Kochi and interesting stops on the drive to Alappuzha. The driver will seek assistance from the car AI for this.",
    25: "The driver is looking for adventure sports and thrilling activities along the route from Dehradun to Rishikesh. The driver will seek assistance from the car AI for this.",
    26: "The driver needs recommendations for charming bed and breakfasts and local farms while traveling from Jaipur to Udaipur. The driver will seek assistance from the car AI for this.",
    27: "The driver wants to find the best spots for local crafts and souvenirs in the area of Aizawl and on the way to Shillong. The driver will seek assistance from the car AI for this.",
    28: "The driver seeks information on local historical landmarks and guided tours while traveling from Bhopal to Jabalpur. The driver will seek assistance from the car AI for this.",
    29: "The driver requests suggestions for the best places to experience traditional cuisine during a drive from Bangalore to Mysore. The driver will seek assistance from the car AI for this.",
    30: "The driver wants to explore local parks and family-friendly attractions along the route from Delhi to Agra. The driver will seek assistance from the car AI for this.",
    31: "The driver seeks recommendations for luxury resorts and local spas in the area of Shimla and during the drive to Manali. The driver will seek assistance from the car AI for this.",
    32: "The driver is planning a scenic drive through the Western Ghats and wants to discover local eco-tourism spots and unique wildlife experiences. The driver will seek assistance from the car AI for this.",
    33: "The driver needs to find local culinary festivals and street food vendors along the route from Chennai to Hyderabad. The driver will seek assistance from the car AI for this.",
    34: "The driver is looking for top-rated hiking trails and outdoor adventures in the area of Darjeeling and during the drive to Gangtok. The driver will seek assistance from the car AI for this.",
    35: "The driver requests recommendations for historic monuments and local museums during a road trip from Delhi to Lucknow. The driver will seek assistance from the car AI for this.",
    36: "The driver wants to find popular shopping streets and local markets in the area of Pune and on the route to Nashik. The driver will seek assistance from the car AI for this.",
    37: "The driver seeks dining recommendations for vegan restaurants while traveling from Bangalore to Mangalore. The driver will seek assistance from the car AI for this.",
    38: "The driver is interested in local music venues and nightlife options while driving from Hyderabad to Chennai. The driver will seek assistance from the car AI for this.",
    39: "The driver requests suggestions for scenic picnic spots and local attractions during a drive from Kochi to Kovalam. The driver will seek assistance from the car AI for this.",
    40: "The driver wants to find top-rated local seafood restaurants and must-visit attractions in the area of Visakhapatnam and along the drive to Chennai. The driver will seek assistance from the car AI for this.",
    41: "The driver seeks recommendations for local farms and agritourism experiences while traveling from Jaipur to Agra. The driver will seek assistance from the car AI for this.",
    42: "The driver is looking for cultural landmarks and traditional performances in the area of Amritsar and on the route to Chandigarh. The driver will seek assistance from the car AI for this.",
    43: "The driver wants to find local art galleries and craft markets in the area of Jaipur and during the drive to Udaipur. The driver will seek assistance from the car AI for this.",
    44: "The driver requests information on family-friendly resorts and local adventure parks while traveling from Manali to Leh. The driver will seek assistance from the car AI for this.",
    45: "The driver seeks recommendations for local cultural tours and historical landmarks during a road trip from Delhi to Haridwar. The driver will seek assistance from the car AI for this.",
    46: "The driver wants to explore local wildlife sanctuaries and natural parks on the route from Pune to Goa. The driver will seek assistance from the car AI for this.",
    47: "The driver is interested in finding local breweries and tasting experiences in the area of Bangalore and on the way to Coorg. The driver will seek assistance from the car AI for this.",
    48: "The driver requests recommendations for local markets and food festivals along the route from Mumbai to Surat. The driver will seek assistance from the car AI for this.",
    49: "The driver seeks to find top-rated local theaters and live performance venues while traveling from Chennai to Bengaluru. The driver will seek assistance from the car AI for this.",
    50: "The driver wants to find relaxing spots and local wellness centers in the area of Pondicherry and on the way to Chennai. The driver will seek assistance from the car AI for this.",
    51: "The driver requests suggestions for local farmers' markets and organic food options while traveling from Delhi to Haridwar. The driver will seek assistance from the car AI for this.",
    52: "The driver is interested in discovering local craft breweries and unique drinking spots on the route from Mumbai to Goa. The driver will seek assistance from the car AI for this.",
    53: "The driver seeks recommendations for scenic drives and local natural wonders while traveling from Shimla to Manali. The driver will seek assistance from the car AI for this.",
    54: "The driver wants to find local coffee shops and bakeries along the route from Kolkata to Guwahati. The driver will seek assistance from the car AI for this.",
    55: "The driver is looking for unique cultural experiences and traditional art forms in the area of Lucknow and on the way to Delhi. The driver will seek assistance from the car AI for this.",
    56: "The driver requests suggestions for the best local food trucks and street food vendors during a road trip from Hyderabad to Pune. The driver will seek assistance from the car AI for this.",
    57: "The driver wants to explore local historical sites and architecture while traveling from Agra to Jaipur. The driver will seek assistance from the car AI for this.",
    58: "The driver seeks recommendations for family-friendly museums and educational attractions on the route from Delhi to Amritsar. The driver will seek assistance from the car AI for this.",
    59: "The driver is interested in discovering local fishing spots and seafood restaurants along the way from Chennai to Pondicherry. The driver will seek assistance from the car AI for this.",
    60: "The driver wants to find local parks and outdoor leisure activities in the area of Bangalore and on the route to Mangalore. The driver will seek assistance from the car AI for this.",
    61: "The driver requests recommendations for local artisan markets and craft shops while traveling from Jaipur to Delhi. The driver will seek assistance from the car AI for this.",
    62: "The driver is looking for top-rated local pubs and nightlife options in the area of Mumbai and on the route to Pune. The driver will seek assistance from the car AI for this.",
    63: "The driver seeks recommendations for scenic lookout points and local nature reserves while traveling from Hyderabad to Goa. The driver will seek assistance from the car AI for this.",
    64: "The driver wants to explore local culinary traditions and popular eateries in the area of Aizawl and on the route to Guwahati. The driver will seek assistance from the car AI for this.",
    65: "The driver requests suggestions for unique local festivals and community events while driving from Delhi to Shimla. The driver will seek assistance from the car AI for this.",
    66: "The driver seeks to find cozy bed and breakfasts and local art galleries while traveling from Udaipur to Jodhpur. The driver will seek assistance from the car AI for this.",
    67: "The driver wants to find local adventure activities and outdoor excursions in the area of Coorg and on the drive from Bangalore. The driver will seek assistance from the car AI for this.",
    68: "The driver is interested in discovering unique local cuisine and food tours along the route from Ahmedabad to Surat. The driver will seek assistance from the car AI for this.",
    69: "The driver requests recommendations for top local attractions and cultural landmarks while traveling from Delhi to Agra. The driver will seek assistance from the car AI for this.",
    70: "The driver seeks dining options for vegan cuisine and health-conscious eateries while traveling from Chennai to Bangalore. The driver will seek assistance from the car AI for this.",
    71: "The driver wants to explore local historical landmarks and heritage sites while traveling from Hyderabad to Jaipur. The driver will seek assistance from the car AI for this.",
    72: "The driver requests suggestions for local parks and recreational areas along the route from Mumbai to Goa. The driver will seek assistance from the car AI for this.",
    73: "The driver seeks recommendations for local craft breweries and tasting experiences while driving from Bangalore to Coorg. The driver will seek assistance from the car AI for this.",
    74: "The driver is looking for top-rated local seafood restaurants and must-visit attractions in the area of Visakhapatnam and on the route to Chennai. The driver will seek assistance from the car AI for this.",
    75: "The driver wants to find local wellness retreats and relaxation spots while traveling from Kochi to Kovalam. The driver will seek assistance from the car AI for this.",
    76: "The driver requests suggestions for local art galleries and craft markets in the area of Jaipur and on the route to Udaipur. The driver will seek assistance from the car AI for this.",
    77: "The driver seeks to discover local historic sites and museums while traveling from Delhi to Amritsar. The driver will seek assistance from the car AI for this.",
    78: "The driver wants to find popular local events and entertainment venues while traveling from Chennai to Hyderabad. The driver will seek assistance from the car AI for this.",
    79: "The driver requests recommendations for top-rated local dining options and attractions along the route from Delhi to Jaipur. The driver will seek assistance from the car AI for this.",
    80: "The driver is interested in finding local farm-to-table restaurants and agricultural tours while driving from Bangalore to Mysore. The driver will seek assistance from the car AI for this.",
    81: "The driver seeks recommendations for scenic driving routes and local nature spots while traveling from Shimla to Manali. The driver will seek assistance from the car AI for this.",
    82: "The driver wants to explore local street food vendors and must-try dishes in the area of Kolkata and during the drive to Guwahati. The driver will seek assistance from the car AI for this.",
    83: "The driver requests suggestions for relaxing spas and wellness centers while traveling from Delhi to Jaipur. The driver will seek assistance from the car AI for this.",
    84: "The driver is interested in discovering local music festivals and cultural events along the route from Chennai to Pondicherry. The driver will seek assistance from the car AI for this.",
    85: "The driver seeks recommendations for local shopping areas and unique craft stores in the area of Pune and on the way to Goa. The driver will seek assistance from the car AI for this.",
    86: "The driver wants to find top-rated local art studios and galleries while traveling from Mumbai to Ahmedabad. The driver will seek assistance from the car AI for this.",
    87: "The driver requests suggestions for family-friendly attractions and fun activities during a road trip from Delhi to Haridwar. The driver will seek assistance from the car AI for this.",
    88: "The driver is interested in finding local food markets and culinary tours while traveling from Bangalore to Coorg. The driver will seek assistance from the car AI for this.",
    89: "The driver seeks recommendations for unique local experiences and outdoor adventures while traveling from Delhi to Shimla. The driver will seek assistance from the car AI for this.",
    90: "The driver wants to find cozy lodges and bed-and-breakfasts along the route from Jaipur to Udaipur. The driver will seek assistance from the car AI for this.",
    91: "The driver requests suggestions for local historical tours and cultural landmarks while driving from Kolkata to Bhubaneswar. The driver will seek assistance from the car AI for this.",
    92: "The driver is interested in finding local theaters and live performances in the area of Chennai and on the route to Bangalore. The driver will seek assistance from the car AI for this.",
    93: "The driver seeks recommendations for scenic drives and local natural attractions while traveling from Mumbai to Goa. The driver will seek assistance from the car AI for this.",
    94: "The driver wants to explore local cultural sites and traditional performances during a drive from Delhi to Agra. The driver will seek assistance from the car AI for this.",
    95: "The driver requests suggestions for the best local restaurants and sightseeing spots while traveling from Bangalore to Hyderabad. The driver will seek assistance from the car AI for this.",
    96: "The driver seeks recommendations for local wellness centers and relaxing retreats while driving from Chennai to Pondicherry. The driver will seek assistance from the car AI for this.",
    97: "The driver is looking for local outdoor adventure spots and scenic hiking trails while traveling from Dehradun to Rishikesh. The driver will seek assistance from the car AI for this.",
    98: "The driver wants to find top local attractions and historical sites in the area of Amritsar and on the route to Chandigarh. The driver will seek assistance from the car AI for this.",
    99: "The driver requests recommendations for unique local dining experiences and food tours while traveling from Mumbai to Surat. The driver will seek assistance from the car AI for this.",
    100: "The driver is looking for the best local coffee shops and breakfast spots along the route while driving from Delhi to Jaipur. The driver will seek assistance from the car AI for this."
}
