contexts = {
    1: "The driver wants to plan a scenic route with multiple stops from Mumbai to Goa. The driver will seek assistance from the car AI for this.",
    2: "The driver wants to find the shortest route from Delhi to Agra, avoiding heavy traffic zones. The driver will seek assistance from the car AI for this.",
    3: "The driver needs to locate nearby charging stations during a trip from Chennai to Pondicherry. The driver will seek assistance from the car AI for this.",
    4: "The driver wants to explore alternate routes from Bengaluru to Hyderabad to avoid roadworks. The driver will seek assistance from the car AI for this.",
    5: "The driver wants to get directions for a road trip from Kolkata to Darjeeling, including stops for tea gardens. The driver will seek assistance from the car AI for this.",
    6: "The driver needs to find the fastest route from Jaipur to Udaipur, considering current traffic conditions. The driver will seek assistance from the car AI for this.",
    7: "The driver wants to locate nearby hotels on the way from Surat to Ahmedabad. The driver will seek assistance from the car AI for this.",
    8: "The driver needs to plan a route from Pune to Matheran with scenic viewpoints. The driver will seek assistance from the car AI for this.",
    9: "The driver wants to find the best route from Varanasi to Lucknow, avoiding tolls. The driver will seek assistance from the car AI for this.",
    10: "The driver wants to get directions from Mumbai to Nashik, including pit stops at local vineyards. The driver will seek assistance from the car AI for this.",
    11: "The driver needs to find nearby restaurants on a trip from Bangalore to Mysore. The driver will seek assistance from the car AI for this.",
    12: "The driver wants to explore alternative routes from Delhi to Chandigarh to avoid traffic congestion. The driver will seek assistance from the car AI for this.",
    13: "The driver wants to plan a route with multiple heritage sites from Jaipur to Ajmer. The driver will seek assistance from the car AI for this.",
    14: "The driver needs to locate the nearest medical facilities on the route from Kolkata to Bhubaneswar. The driver will seek assistance from the car AI for this.",
    15: "The driver wants to find the most efficient route from Mumbai to Pune during peak hours. The driver will seek assistance from the car AI for this.",
    16: "The driver needs to get directions for a trip from Delhi to Shimla, including stops for local attractions. The driver will seek assistance from the car AI for this.",
    17: "The driver wants to explore alternate routes from Chennai to Coimbatore to avoid roadblocks. The driver will seek assistance from the car AI for this.",
    18: "The driver needs to find the best route from Bangalore to Hubli with minimum travel time. The driver will seek assistance from the car AI for this.",
    19: "The driver wants to locate nearby public restrooms on a trip from Hyderabad to Vijayawada. The driver will seek assistance from the car AI for this.",
    20: "The driver needs to plan a route from Pune to Lonavala with scenic mountain views. The driver will seek assistance from the car AI for this.",
    21: "The driver wants to find the shortest route from Mumbai to Surat, avoiding toll roads. The driver will seek assistance from the car AI for this.",
    22: "The driver needs to locate nearby EV charging stations on a trip from Delhi to Agra. The driver will seek assistance from the car AI for this.",
    23: "The driver wants to explore alternative routes from Bangalore to Chennai to avoid traffic jams. The driver will seek assistance from the car AI for this.",
    24: "The driver needs to get directions from Jaipur to Jodhpur with stops at local forts. The driver will seek assistance from the car AI for this.",
    25: "The driver wants to find nearby ATMs on the way from Mumbai to Goa. The driver will seek assistance from the car AI for this.",
    26: "The driver needs to plan a scenic route from Delhi to Agra with views of the Yamuna River. The driver will seek assistance from the car AI for this.",
    27: "The driver wants to explore alternative routes from Chennai to Tirupati to avoid traffic. The driver will seek assistance from the car AI for this.",
    28: "The driver needs to locate nearby gas stations during a trip from Hyderabad to Bengaluru. The driver will seek assistance from the car AI for this.",
    29: "The driver wants to get directions from Kolkata to Puri with stops at local temples. The driver will seek assistance from the car AI for this.",
    30: "The driver needs to find the fastest route from Delhi to Jaipur, considering real-time traffic updates. The driver will seek assistance from the car AI for this.",
    31: "The driver wants to plan a trip from Pune to Goa, including stops at popular beaches. The driver will seek assistance from the car AI for this.",
    32: "The driver needs to locate the nearest parking facilities on a trip from Mumbai to Nashik. The driver will seek assistance from the car AI for this.",
    33: "The driver wants to find the most efficient route from Bangalore to Mysore during peak traffic hours. The driver will seek assistance from the car AI for this.",
    34: "The driver needs to explore alternate routes from Delhi to Chandigarh to avoid construction zones. The driver will seek assistance from the car AI for this.",
    35: "The driver wants to get directions from Hyderabad to Warangal with scenic spots along the way. The driver will seek assistance from the car AI for this.",
    36: "The driver needs to find the best route from Chennai to Kanyakumari, avoiding busy intersections. The driver will seek assistance from the car AI for this.",
    37: "The driver wants to locate nearby cafes on the route from Delhi to Jaipur. The driver will seek assistance from the car AI for this.",
    38: "The driver needs to plan a trip from Bangalore to Coorg with stops at coffee plantations. The driver will seek assistance from the car AI for this.",
    39: "The driver wants to explore alternate routes from Mumbai to Pune to avoid traffic jams. The driver will seek assistance from the car AI for this.",
    40: "The driver needs to get directions from Chennai to Bangalore with minimal stops. The driver will seek assistance from the car AI for this.",
    41: "The driver wants to find the best route from Surat to Vadodara with minimal traffic. The driver will seek assistance from the car AI for this.",
    42: "The driver needs to locate nearby rest areas on a trip from Delhi to Agra. The driver will seek assistance from the car AI for this.",
    43: "The driver wants to get directions from Kolkata to Siliguri, including stops at tea estates. The driver will seek assistance from the car AI for this.",
    44: "The driver needs to plan a scenic drive from Mumbai to Alibaug with coastal views. The driver will seek assistance from the car AI for this.",
    45: "The driver wants to explore alternative routes from Delhi to Lucknow to avoid toll booths. The driver will seek assistance from the car AI for this.",
    46: "The driver needs to find the shortest route from Bengaluru to Madurai with the least amount of traffic. The driver will seek assistance from the car AI for this.",
    47: "The driver wants to locate nearby hospitals on the route from Pune to Nashik. The driver will seek assistance from the car AI for this.",
    48: "The driver needs to get directions from Chennai to Tiruvannamalai, including stops at local landmarks. The driver will seek assistance from the car AI for this.",
    49: "The driver wants to explore alternate routes from Mumbai to Vadodara to avoid road closures. The driver will seek assistance from the car AI for this.",
    50: "The driver needs to find the fastest route from Delhi to Haridwar, considering current traffic conditions. The driver will seek assistance from the car AI for this.",
    51: "The driver wants to get directions for a road trip from Bangalore to Goa with stops at popular beaches. The driver will seek assistance from the car AI for this.",
    52: "The driver needs to locate nearby service stations on the way from Hyderabad to Visakhapatnam. The driver will seek assistance from the car AI for this.",
    53: "The driver wants to find the most efficient route from Mumbai to Aurangabad during peak traffic hours. The driver will seek assistance from the car AI for this.",
    54: "The driver needs to explore alternative routes from Jaipur to Jaisalmer to avoid traffic congestion. The driver will seek assistance from the car AI for this.",
    55: "The driver wants to get directions from Chennai to Pondicherry, including stops at local tourist spots. The driver will seek assistance from the car AI for this.",
    56: "The driver needs to plan a route from Delhi to Amritsar with stops at historical sites. The driver will seek assistance from the car AI for this.",
    57: "The driver wants to find nearby ATMs on the route from Bengaluru to Coimbatore. The driver will seek assistance from the car AI for this.",
    58: "The driver needs to locate rest areas on the way from Chennai to Kanyakumari. The driver will seek assistance from the car AI for this.",
    59: "The driver wants to explore alternate routes from Mumbai to Surat to avoid heavy traffic. The driver will seek assistance from the car AI for this.",
    60: "The driver needs to get directions from Hyderabad to Kakinada, including stops at local attractions. The driver will seek assistance from the car AI for this.",
    61: "The driver wants to find the best route from Delhi to Jaipur during peak traffic times. The driver will seek assistance from the car AI for this.",
    62: "The driver needs to locate nearby hotels on the way from Bengaluru to Hyderabad. The driver will seek assistance from the car AI for this.",
    63: "The driver wants to get directions for a road trip from Mumbai to Delhi, including scenic stops along the way. The driver will seek assistance from the car AI for this.",
    64: "The driver needs to find the most efficient route from Chennai to Madurai with minimal travel time. The driver will seek assistance from the car AI for this.",
    65: "The driver wants to explore alternate routes from Kolkata to Patna to avoid roadblocks. The driver will seek assistance from the car AI for this.",
    66: "The driver needs to get directions from Pune to Goa with scenic coastal views. The driver will seek assistance from the car AI for this.",
    67: "The driver wants to find the best route from Bangalore to Mysore, avoiding toll roads. The driver will seek assistance from the car AI for this.",
    68: "The driver needs to locate nearby restaurants on a trip from Hyderabad to Chennai. The driver will seek assistance from the car AI for this.",
    69: "The driver wants to get directions from Delhi to Jaipur, including stops for local cuisine. The driver will seek assistance from the car AI for this.",
    70: "The driver needs to plan a route from Mumbai to Alibaug with minimal traffic delays. The driver will seek assistance from the car AI for this.",
    71: "The driver wants to explore alternative routes from Chennai to Coimbatore to avoid road closures. The driver will seek assistance from the car AI for this.",
    72: "The driver needs to find the most efficient route from Surat to Vadodara, considering real-time traffic updates. The driver will seek assistance from the car AI for this.",
    73: "The driver wants to locate nearby gas stations during a trip from Bangalore to Hubli. The driver will seek assistance from the car AI for this.",
    74: "The driver needs to get directions from Kolkata to Gangtok, including stops at scenic viewpoints. The driver will seek assistance from the car AI for this.",
    75: "The driver wants to plan a scenic route from Delhi to Shimla with multiple tourist spots. The driver will seek assistance from the car AI for this.",
    76: "The driver needs to find the best route from Mumbai to Nagpur, avoiding traffic congestion. The driver will seek assistance from the car AI for this.",
    77: "The driver wants to explore alternate routes from Hyderabad to Vijayawada to avoid heavy traffic. The driver will seek assistance from the car AI for this.",
    78: "The driver needs to get directions from Pune to Aurangabad with stops at local landmarks. The driver will seek assistance from the car AI for this.",
    79: "The driver wants to find the shortest route from Chennai to Tiruchirappalli, avoiding toll roads. The driver will seek assistance from the car AI for this.",
    80: "The driver needs to plan a route from Bangalore to Coorg with stops at coffee estates. The driver will seek assistance from the car AI for this.",
    81: "The driver wants to explore alternative routes from Delhi to Agra to avoid traffic congestion. The driver will seek assistance from the car AI for this.",
    82: "The driver needs to find the best route from Chennai to Thanjavur with minimal stops. The driver will seek assistance from the car AI for this.",
    83: "The driver wants to get directions from Mumbai to Surat with stops at local attractions. The driver will seek assistance from the car AI for this.",
    84: "The driver needs to locate nearby rest areas on a trip from Delhi to Amritsar. The driver will seek assistance from the car AI for this.",
    85: "The driver wants to find the most efficient route from Kolkata to Jamshedpur, avoiding construction zones. The driver will seek assistance from the car AI for this.",
    86: "The driver needs to get directions from Bangalore to Mangalore with stops at scenic viewpoints. The driver will seek assistance from the car AI for this.",
    87: "The driver wants to explore alternative routes from Hyderabad to Pune to avoid traffic jams. The driver will seek assistance from the car AI for this.",
    88: "The driver needs to find the shortest route from Delhi to Chandigarh during peak traffic hours. The driver will seek assistance from the car AI for this.",
    89: "The driver wants to get directions from Chennai to Kanchipuram with stops at local temples. The driver will seek assistance from the car AI for this.",
    90: "The driver needs to locate nearby hospitals on the route from Mumbai to Aurangabad. The driver will seek assistance from the car AI for this.",
    91: "The driver wants to explore alternate routes from Jaipur to Delhi to avoid heavy traffic. The driver will seek assistance from the car AI for this.",
    92: "The driver needs to get directions from Bengaluru to Mysore, including stops for local cuisine. The driver will seek assistance from the car AI for this.",
    93: "The driver wants to find the most efficient route from Surat to Vadodara, avoiding roadblocks. The driver will seek assistance from the car AI for this.",
    94: "The driver needs to plan a scenic route from Delhi to Haridwar with stops at religious sites. The driver will seek assistance from the car AI for this.",
    95: "The driver wants to get directions from Mumbai to Daman with minimal traffic delays. The driver will seek assistance from the car AI for this.",
    96: "The driver needs to find the best route from Chennai to Madurai, including stops at historical sites. The driver will seek assistance from the car AI for this.",
    97: "The driver wants to explore alternate routes from Kolkata to Bhubaneswar to avoid traffic congestion. The driver will seek assistance from the car AI for this.",
    98: "The driver needs to get directions from Hyderabad to Tirupati with scenic viewpoints along the way. The driver will seek assistance from the car AI for this.",
    99: "The driver wants to find the most efficient route from Bengaluru to Coimbatore during peak traffic times. The driver will seek assistance from the car AI for this.",
    100: "The driver needs to plan a route from Delhi to Jaipur with stops at local landmarks and attractions. The driver will seek assistance from the car AI for this."
}
