context = {
    1: "The driver wants to activate lane-keeping assist while driving on the highway to Mumbai. The driver will seek assistance from the car AI for this.",
    2: "The driver needs a status check on all safety features before embarking on a long road trip to Goa. The driver will seek assistance from the car AI for this.",
    3: "The driver wants to enable speed limit notifications during a drive through Pune. The driver will seek assistance from the car AI for this.",
    4: "The driver requests activation of automatic emergency braking while navigating through heavy traffic in Delhi. The driver will seek assistance from the car AI for this.",
    5: "The driver wants to inquire about blind-spot monitoring before changing lanes on the way to Chandigarh. The driver will seek assistance from the car AI for this.",
    6: "The driver seeks driving tips for foggy conditions when traveling to Shimla. The driver will seek assistance from the car AI for this.",
    7: "The driver wants to check the status of airbags before a long drive to Lucknow. The driver will seek assistance from the car AI for this.",
    8: "The driver needs to enable the car's stability control system while driving through the Western Ghats. The driver will seek assistance from the car AI for this.",
    9: "The driver is looking for tips on safe driving at night during a road trip to Hyderabad. The driver will seek assistance from the car AI for this.",
    10: "The driver wants to be notified if the car drifts out of the lane during a trip to Bangalore. The driver will seek assistance from the car AI for this.",
    11: "The driver needs to locate nearby hospitals in case of an emergency during a drive to Shimla. The driver will seek assistance from the car AI for this.",
    12: "The driver requests first-aid instructions following a minor accident on the way to Chennai. The driver will seek assistance from the car AI for this.",
    13: "The driver wants help calling roadside assistance after a breakdown during a trip to Rishikesh. The driver will seek assistance from the car AI for this.",
    14: "The driver is looking for instructions on handling a tire blowout while driving to Agra. The driver will seek assistance from the car AI for this.",
    15: "The driver needs emergency evacuation routes in case of a natural disaster while traveling through Kerala. The driver will seek assistance from the car AI for this.",
    16: "The driver wants to locate the nearest mechanic for emergency repairs during a trip to Nagpur. The driver will seek assistance from the car AI for this.",
    17: "The driver requests fire safety tips after noticing smoke in the engine while driving to Delhi. The driver will seek assistance from the car AI for this.",
    18: "The driver needs help changing a flat tire while on the way to Bangalore. The driver will seek assistance from the car AI for this.",
    19: "The driver wants directions to the nearest police station after witnessing an accident on the highway to Pune. The driver will seek assistance from the car AI for this.",
    20: "The driver requests the AI to alert emergency contacts following a major breakdown in a remote area near Ladakh. The driver will seek assistance from the car AI for this.",
    21: "The driver wants to activate the collision warning system while driving in heavy rain on the way to Chennai. The driver will seek assistance from the car AI for this.",
    22: "The driver seeks advice on driving safely through a snowstorm during a trip to Manali. The driver will seek assistance from the car AI for this.",
    23: "The driver needs to check the status of the car’s tire pressure monitoring system before heading out to Jaipur. The driver will seek assistance from the car AI for this.",
    24: "The driver wants to enable traction control while driving on icy roads near Shimla. The driver will seek assistance from the car AI for this.",
    25: "The driver requests guidance on how to use the emergency hazard lights after an accident on the way to Mumbai. The driver will seek assistance from the car AI for this.",
    26: "The driver needs to find the nearest tow truck service after their car breaks down in a rural area near Rishikesh. The driver will seek assistance from the car AI for this.",
    27: "The driver seeks advice on how to handle engine overheating during a drive through the desert in Rajasthan. The driver will seek assistance from the car AI for this.",
    28: "The driver wants to activate the rearview camera for parallel parking in a busy area of Bangalore. The driver will seek assistance from the car AI for this.",
    29: "The driver requests information on how to use the car’s built-in first-aid kit after a minor injury while driving to Goa. The driver will seek assistance from the car AI for this.",
    30: "The driver wants to enable forward collision warning while navigating through congested traffic in Delhi. The driver will seek assistance from the car AI for this.",
    31: "The driver needs to locate nearby gas stations due to running low on fuel while traveling to Hyderabad. The driver will seek assistance from the car AI for this.",
    32: "The driver seeks instructions for using the car’s emergency alert system after encountering a road hazard on the way to Pune. The driver will seek assistance from the car AI for this.",
    33: "The driver wants to activate the automatic high beams for night driving during a road trip to Agra. The driver will seek assistance from the car AI for this.",
    34: "The driver needs to check the status of the car's anti-lock braking system before driving in wet conditions to Bangalore. The driver will seek assistance from the car AI for this.",
    35: "The driver requests tips for safe driving through a sandstorm during a trip to Jaisalmer. The driver will seek assistance from the car AI for this.",
    36: "The driver wants to activate lane departure warning while driving through a winding road in the Western Ghats. The driver will seek assistance from the car AI for this.",
    37: "The driver seeks emergency procedures for handling a gas leak in the vehicle while on the highway to Chennai. The driver will seek assistance from the car AI for this.",
    38: "The driver wants help locating the nearest car rental service after their vehicle breaks down in an unfamiliar city. The driver will seek assistance from the car AI for this.",
    39: "The driver needs instructions for activating the car’s child safety locks before a family trip to Delhi. The driver will seek assistance from the car AI for this.",
    40: "The driver requests guidance on how to use the car’s panic button in case of an emergency during a road trip to Goa. The driver will seek assistance from the car AI for this.",
    41: "The driver wants to activate the adaptive cruise control while driving on the expressway to Mumbai. The driver will seek assistance from the car AI for this.",
    42: "The driver seeks advice on driving safely through a thunderstorm during a trip to Bangalore. The driver will seek assistance from the car AI for this.",
    43: "The driver needs to check the status of the car’s automatic parking assist before arriving at a crowded event in Delhi. The driver will seek assistance from the car AI for this.",
    44: "The driver requests activation of the car’s collision mitigation system while driving through dense fog near Shimla. The driver will seek assistance from the car AI for this.",
    45: "The driver wants to locate the nearest emergency service station after a minor collision on the way to Hyderabad. The driver will seek assistance from the car AI for this.",
    46: "The driver needs instructions on how to use the car’s tire repair kit after a puncture on the highway to Agra. The driver will seek assistance from the car AI for this.",
    47: "The driver requests information on the car’s road hazard alert system while driving through rural areas in Rajasthan. The driver will seek assistance from the car AI for this.",
    48: "The driver wants to activate the car’s front and rear sensors for parking in a tight spot in Bangalore. The driver will seek assistance from the car AI for this.",
    49: "The driver seeks help locating the nearest emergency exit routes in case of a fire while driving through Delhi. The driver will seek assistance from the car AI for this.",
    50: "The driver wants tips for maintaining control of the vehicle on a slippery road during a trip to Manali. The driver will seek assistance from the car AI for this.",
    51: "The driver requests assistance with activating the car’s lane change assist feature while navigating through city traffic in Mumbai. The driver will seek assistance from the car AI for this.",
    52: "The driver needs emergency contact numbers in case of a severe accident while traveling to Chennai. The driver will seek assistance from the car AI for this.",
    53: "The driver wants guidance on handling a brake failure during a trip through the Western Ghats. The driver will seek assistance from the car AI for this.",
    54: "The driver seeks advice on how to handle a sudden loss of power while driving through the desert in Rajasthan. The driver will seek assistance from the car AI for this.",
    55: "The driver wants to activate the rear cross-traffic alert while reversing out of a parking space in a busy area of Delhi. The driver will seek assistance from the car AI for this.",
    56: "The driver needs to check the car’s emergency preparedness features before a road trip to Goa. The driver will seek assistance from the car AI for this.",
    57: "The driver requests instructions for activating the car’s emergency braking system while navigating through heavy traffic in Mumbai. The driver will seek assistance from the car AI for this.",
    58: "The driver wants help finding the nearest roadside assistance service after an engine failure on the highway to Hyderabad. The driver will seek assistance from the car AI for this.",
    59: "The driver seeks advice on using the car’s emergency communication system during a power outage while driving to Bangalore. The driver will seek assistance from the car AI for this.",
    60: "The driver wants to activate the car’s adaptive headlights for improved visibility during a nighttime drive to Shimla. The driver will seek assistance from the car AI for this.",
    61: "The driver needs to check the status of the car’s collision avoidance system before a long drive to Agra. The driver will seek assistance from the car AI for this.",
    62: "The driver requests guidance on safely maneuvering through a flooded area during a trip to Kerala. The driver will seek assistance from the car AI for this.",
    63: "The driver wants to activate the car’s side impact airbags before driving through a densely populated area in Delhi. The driver will seek assistance from the car AI for this.",
    64: "The driver seeks help finding the nearest shelter after being caught in a severe thunderstorm while driving to Chennai. The driver will seek assistance from the car AI for this.",
    65: "The driver needs instructions on how to use the car’s emergency flares after a breakdown in a remote area of Rajasthan. The driver will seek assistance from the car AI for this.",
    66: "The driver requests information on the car’s emergency steering assist feature while navigating through a narrow mountain pass in Himachal Pradesh. The driver will seek assistance from the car AI for this.",
    67: "The driver wants tips for maintaining vehicle stability while driving on a gravel road during a trip to Jaisalmer. The driver will seek assistance from the car AI for this.",
    68: "The driver needs to check the status of the car’s traction control system before driving in snowy conditions near Shimla. The driver will seek assistance from the car AI for this.",
    69: "The driver requests instructions on using the car’s onboard emergency navigation system after a road accident on the way to Bangalore. The driver will seek assistance from the car AI for this.",
    70: "The driver wants to activate the car’s automatic emergency call feature while driving through a remote area in Ladakh. The driver will seek assistance from the car AI for this.",
    71: "The driver seeks advice on how to handle a steering issue during a long trip through the Western Ghats. The driver will seek assistance from the car AI for this.",
    72: "The driver needs to locate the nearest fire department after noticing smoke from the engine while driving to Delhi. The driver will seek assistance from the car AI for this.",
    73: "The driver wants to enable the car’s adaptive cruise control while driving through heavy traffic in Chennai. The driver will seek assistance from the car AI for this.",
    74: "The driver requests help with activating the car’s collision detection system after a minor fender-bender on the highway to Mumbai. The driver will seek assistance from the car AI for this.",
    75: "The driver seeks instructions for using the car’s roadside emergency kit after a tire blowout during a road trip to Agra. The driver will seek assistance from the car AI for this.",
    76: "The driver wants tips for navigating through dense fog while driving to Bangalore. The driver will seek assistance from the car AI for this.",
    77: "The driver needs to check the status of the car’s emergency locking system before a trip to Delhi. The driver will seek assistance from the car AI for this.",
    78: "The driver requests guidance on safely driving through a sandstorm during a journey to Jaisalmer. The driver will seek assistance from the car AI for this.",
    79: "The driver wants to activate the car’s automatic lane centering feature while traveling through a busy street in Mumbai. The driver will seek assistance from the car AI for this.",
    80: "The driver seeks advice on handling a fuel leak during a drive through the rural areas of Rajasthan. The driver will seek assistance from the car AI for this.",
    81: "The driver needs instructions for using the car’s onboard fire extinguisher after noticing a small engine fire while driving to Chennai. The driver will seek assistance from the car AI for this.",
    82: "The driver wants to activate the car’s collision avoidance system while driving in a hailstorm on the way to Hyderabad. The driver will seek assistance from the car AI for this.",
    83: "The driver requests information on the car’s emergency braking system while navigating through heavy rain in Delhi. The driver will seek assistance from the car AI for this.",
    84: "The driver needs to locate the nearest ambulance service after a serious accident while driving to Agra. The driver will seek assistance from the car AI for this.",
    85: "The driver wants to activate the car’s blind-spot alert system while driving on a multi-lane highway in Mumbai. The driver will seek assistance from the car AI for this.",
    86: "The driver seeks advice on handling a stuck accelerator during a high-speed drive on the expressway to Bangalore. The driver will seek assistance from the car AI for this.",
    87: "The driver needs help finding the nearest car repair service after experiencing engine trouble while traveling to Hyderabad. The driver will seek assistance from the car AI for this.",
    88: "The driver requests tips for safe driving on a poorly lit rural road during a trip to Shimla. The driver will seek assistance from the car AI for this.",
    89: "The driver wants to activate the car’s parking assist feature while parking in a crowded area of Chennai. The driver will seek assistance from the car AI for this.",
    90: "The driver seeks guidance on handling an electrical failure during a road trip to Goa. The driver will seek assistance from the car AI for this.",
    91: "The driver needs to locate the nearest police station after witnessing a hit-and-run accident while driving to Delhi. The driver will seek assistance from the car AI for this.",
    92: "The driver wants to activate the car’s stability control system while navigating through a sharp curve in the Western Ghats. The driver will seek assistance from the car AI for this.",
    93: "The driver requests information on how to use the car’s emergency lighting system after a breakdown in a remote area of Ladakh. The driver will seek assistance from the car AI for this.",
    94: "The driver needs help finding a safe location to stop after experiencing sudden brake failure on the highway to Agra. The driver will seek assistance from the car AI for this.",
    95: "The driver seeks advice on driving safely through a dust storm during a trip to Jaisalmer. The driver will seek assistance from the car AI for this.",
    96: "The driver wants to activate the car’s emergency collision alert system while driving through foggy conditions in Shimla. The driver will seek assistance from the car AI for this.",
    97: "The driver requests guidance on handling a fuel gauge malfunction while traveling to Bangalore. The driver will seek assistance from the car AI for this.",
    98: "The driver needs to locate the nearest emergency medical service after a car accident on the way to Chennai. The driver will seek assistance from the car AI for this.",
    99: "The driver wants to activate the car’s side curtain airbags before driving through a busy city center in Mumbai. The driver will seek assistance from the car AI for this.",
    100: "The driver seeks advice on safely handling a sudden engine stall during a road trip through the desert in Rajasthan. The driver will seek assistance from the car AI for this."
}
