contexts = {
    1: "The driver wants to check the rain forecast for the drive from Delhi to Agra. The driver will seek assistance from the car AI for this.",
    2: "The driver wants to know if there are any weather advisories on the route from Mumbai to Pune. The driver will seek assistance from the car AI for this.",
    3: "The driver needs the current temperature and visibility conditions for a road trip from Bangalore to Mysore. The driver will seek assistance from the car AI for this.",
    4: "The driver is looking for snow conditions on the path from Shimla to Manali. The driver will seek assistance from the car AI for this.",
    5: "The driver wants to get wind speed updates before heading out from Chennai to Coimbatore. The driver will seek assistance from the car AI for this.",
    6: "The driver needs to check the UV index for the trip from Jaipur to Udaipur. The driver will seek assistance from the car AI for this.",
    7: "The driver wants to know the fog density on the drive from Dehradun to Haridwar. The driver will seek assistance from the car AI for this.",
    8: "The driver is looking for extreme heat alerts for a journey from Hyderabad to Visakhapatnam. The driver will seek assistance from the car AI for this.",
    9: "The driver wants to check for thunderstorm warnings on the route from Kolkata to Siliguri. The driver will seek assistance from the car AI for this.",
    10: "The driver needs current humidity levels for the drive from Ahmedabad to Surat. The driver will seek assistance from the car AI for this.",
    11: "The driver is looking for rain chances on the journey from Goa to Mangalore. The driver will seek assistance from the car AI for this.",
    12: "The driver wants to know if there are any roadblocks due to landslides on the route from Srinagar to Leh. The driver will seek assistance from the car AI for this.",
    13: "The driver needs information about the snow forecast for traveling from Manali to Leh. The driver will seek assistance from the car AI for this.",
    14: "The driver is seeking details on wind chill factors for a drive from Chandigarh to Amritsar. The driver will seek assistance from the car AI for this.",
    15: "The driver wants to check if there are any hailstorm warnings on the route from Bengaluru to Chennai. The driver will seek assistance from the car AI for this.",
    16: "The driver needs the current air quality index for the trip from Delhi to Jaipur. The driver will seek assistance from the car AI for this.",
    17: "The driver is looking for high temperature warnings before heading from Pune to Nashik. The driver will seek assistance from the car AI for this.",
    18: "The driver wants to check the rain probability for a drive from Kochi to Calicut. The driver will seek assistance from the car AI for this.",
    19: "The driver needs to know if there are any weather-related travel restrictions on the route from Bhubaneswar to Puri. The driver will seek assistance from the car AI for this.",
    20: "The driver is looking for fog forecast on the journey from Allahabad to Varanasi. The driver will seek assistance from the car AI for this.",
    21: "The driver wants to get updates on cloud cover for the trip from Jaisalmer to Bikaner. The driver will seek assistance from the car AI for this.",
    22: "The driver needs information about possible cyclonic conditions on the route from Visakhapatnam to Chennai. The driver will seek assistance from the car AI for this.",
    23: "The driver is seeking details on road conditions due to recent rainfall on the drive from Ranchi to Jamshedpur. The driver will seek assistance from the car AI for this.",
    24: "The driver wants to know the weather conditions before heading out from Patna to Gaya. The driver will seek assistance from the car AI for this.",
    25: "The driver needs current visibility and temperature for a trip from Bangalore to Hyderabad. The driver will seek assistance from the car AI for this.",
    26: "The driver is looking for information about potential flooding on the route from Mumbai to Nashik. The driver will seek assistance from the car AI for this.",
    27: "The driver wants to check the weather conditions for traveling from Coimbatore to Madurai. The driver will seek assistance from the car AI for this.",
    28: "The driver needs to know if there are any high winds reported on the drive from Nagpur to Raipur. The driver will seek assistance from the car AI for this.",
    29: "The driver is seeking snow accumulation forecasts for a trip from Srinagar to Gulmarg. The driver will seek assistance from the car AI for this.",
    30: "The driver wants to check if there are any weather-related road closures on the route from Amritsar to Jammu. The driver will seek assistance from the car AI for this.",
    31: "The driver needs to know the current weather for a journey from Udaipur to Mount Abu. The driver will seek assistance from the car AI for this.",
    32: "The driver is looking for heatwave alerts before traveling from Pune to Aurangabad. The driver will seek assistance from the car AI for this.",
    33: "The driver wants to check for rain or thunderstorm updates for a drive from Bengaluru to Mangalore. The driver will seek assistance from the car AI for this.",
    34: "The driver needs to know if there are any weather warnings for the route from Jodhpur to Jaisalmer. The driver will seek assistance from the car AI for this.",
    35: "The driver is seeking details on temperature drops for the journey from Shimla to Manali. The driver will seek assistance from the car AI for this.",
    36: "The driver wants to check wind gust speeds for traveling from Chennai to Tiruchirappalli. The driver will seek assistance from the car AI for this.",
    37: "The driver needs to know the risk of fog on the drive from Ludhiana to Amritsar. The driver will seek assistance from the car AI for this.",
    38: "The driver is looking for current weather alerts on the route from Hyderabad to Warangal. The driver will seek assistance from the car AI for this.",
    39: "The driver wants to get information about recent weather conditions before heading from Vadodara to Surat. The driver will seek assistance from the car AI for this.",
    40: "The driver needs to know the likelihood of thunderstorms on the trip from Patna to Muzaffarpur. The driver will seek assistance from the car AI for this.",
    41: "The driver is seeking temperature and humidity updates for the journey from Agra to Kanpur. The driver will seek assistance from the car AI for this.",
    42: "The driver wants to check if there are any road issues due to rain on the drive from Imphal to Dimapur. The driver will seek assistance from the car AI for this.",
    43: "The driver needs information about the wind speed and direction for traveling from Jaipur to Jodhpur. The driver will seek assistance from the car AI for this.",
    44: "The driver is looking for precipitation forecasts on the route from Coimbatore to Tiruppur. The driver will seek assistance from the car AI for this.",
    45: "The driver wants to check the weather and visibility conditions before heading out from Raipur to Bilaspur. The driver will seek assistance from the car AI for this.",
    46: "The driver needs to know if there are any extreme weather warnings on the drive from Agartala to Guwahati. The driver will seek assistance from the car AI for this.",
    47: "The driver is seeking details on rainfall intensity for the journey from Madurai to Kanyakumari. The driver will seek assistance from the car AI for this.",
    48: "The driver wants to get updates on heat index levels for traveling from Mumbai to Vadodara. The driver will seek assistance from the car AI for this.",
    49: "The driver needs to know if there are any weather-related travel advisories on the route from Visakhapatnam to Vijayawada. The driver will seek assistance from the car AI for this.",
    50: "The driver is looking for snow and ice conditions before heading from Leh to Srinagar. The driver will seek assistance from the car AI for this.",
    51: "The driver wants to check the wind speed and direction for the drive from Mumbai to Nashik. The driver will seek assistance from the car AI for this.",
    52: "The driver needs to know the weather and visibility conditions on the route from Delhi to Kanpur. The driver will seek assistance from the car AI for this.",
    53: "The driver is seeking information about recent rainfall and road conditions for the journey from Bangalore to Hyderabad. The driver will seek assistance from the car AI for this.",
    54: "The driver wants to check if there are any travel restrictions due to severe weather on the drive from Ranchi to Patna. The driver will seek assistance from the car AI for this.",
    55: "The driver needs to know if there are any cyclonic weather warnings on the route from Kolkata to Bhubaneswar. The driver will seek assistance from the car AI for this.",
    56: "The driver is looking for fog forecasts and visibility conditions before traveling from Delhi to Agra. The driver will seek assistance from the car AI for this.",
    57: "The driver wants to get updates on temperature and precipitation chances for a drive from Surat to Vadodara. The driver will seek assistance from the car AI for this.",
    58: "The driver needs to know the likelihood of extreme cold weather on the trip from Shimla to Nainital. The driver will seek assistance from the car AI for this.",
    59: "The driver is seeking details on rain and wind speed for traveling from Patna to Gaya. The driver will seek assistance from the car AI for this.",
    60: "The driver wants to check for any weather-related hazards before heading from Mangalore to Coimbatore. The driver will seek assistance from the car AI for this.",
    61: "The driver needs to know if there are any heat alerts on the drive from Chennai to Trichy. The driver will seek assistance from the car AI for this.",
    62: "The driver is looking for rain intensity forecasts for a journey from Pune to Kolhapur. The driver will seek assistance from the car AI for this.",
    63: "The driver wants to get updates on snow accumulation for traveling from Leh to Manali. The driver will seek assistance from the car AI for this.",
    64: "The driver needs to know the risk of roadblocks due to flooding on the route from Bangalore to Coimbatore. The driver will seek assistance from the car AI for this.",
    65: "The driver is seeking temperature and humidity information for the drive from Chennai to Madurai. The driver will seek assistance from the car AI for this.",
    66: "The driver wants to check the wind chill factor for a journey from Agra to Jaipur. The driver will seek assistance from the car AI for this.",
    67: "The driver needs to know if there are any fog warnings on the route from Dehradun to Shimla. The driver will seek assistance from the car AI for this.",
    68: "The driver is looking for current weather conditions for traveling from Hyderabad to Vijayawada. The driver will seek assistance from the car AI for this.",
    69: "The driver wants to get updates on rain forecast for a trip from Imphal to Shillong. The driver will seek assistance from the car AI for this.",
    70: "The driver needs to know if there are any weather alerts for the drive from Udaipur to Jaipur. The driver will seek assistance from the car AI for this.",
    71: "The driver is seeking details on wind speeds and visibility for traveling from Jaisalmer to Bikaner. The driver will seek assistance from the car AI for this.",
    72: "The driver wants to check if there are any severe weather warnings on the route from Cochin to Mangalore. The driver will seek assistance from the car AI for this.",
    73: "The driver needs to know the current rain intensity for the drive from Delhi to Chandigarh. The driver will seek assistance from the car AI for this.",
    74: "The driver is looking for fog and visibility updates for a trip from Kolkata to Siliguri. The driver will seek assistance from the car AI for this.",
    75: "The driver wants to get wind speed and temperature details before heading from Guwahati to Shillong. The driver will seek assistance from the car AI for this.",
    76: "The driver needs information about extreme heat for traveling from Surat to Rajkot. The driver will seek assistance from the car AI for this.",
    77: "The driver is seeking updates on snow forecasts and road conditions for the journey from Srinagar to Gulmarg. The driver will seek assistance from the car AI for this.",
    78: "The driver wants to check if there are any flood alerts on the route from Bangalore to Mysore. The driver will seek assistance from the car AI for this.",
    79: "The driver needs to know the risk of rain and high winds for the trip from Chennai to Bengaluru. The driver will seek assistance from the car AI for this.",
    80: "The driver is looking for information about the air quality index for traveling from Mumbai to Pune. The driver will seek assistance from the car AI for this.",
    81: "The driver wants to get updates on cloud cover and precipitation chances before heading from Jodhpur to Jaisalmer. The driver will seek assistance from the car AI for this.",
    82: "The driver needs to know if there are any heatwave alerts on the drive from Ahmedabad to Surat. The driver will seek assistance from the car AI for this.",
    83: "The driver is seeking information about wind gusts and temperature for the route from Delhi to Jaipur. The driver will seek assistance from the car AI for this.",
    84: "The driver wants to check rain chances and temperature for traveling from Patna to Darbhanga. The driver will seek assistance from the car AI for this.",
    85: "The driver needs details on visibility and fog conditions for a journey from Mumbai to Goa. The driver will seek assistance from the car AI for this.",
    86: "The driver is looking for weather conditions and warnings on the route from Shimla to Solan. The driver will seek assistance from the car AI for this.",
    87: "The driver wants to get updates on temperature and wind conditions before heading from Kolkata to Durgapur. The driver will seek assistance from the car AI for this.",
    88: "The driver needs to know if there are any weather advisories for traveling from Chennai to Tirunelveli. The driver will seek assistance from the car AI for this.",
    89: "The driver is seeking information about recent rainfall and road conditions for the journey from Surat to Vadodara. The driver will seek assistance from the car AI for this.",
    90: "The driver wants to check for heat index levels and air quality before traveling from Bangalore to Coimbatore. The driver will seek assistance from the car AI for this.",
    91: "The driver needs to know the risk of thunderstorms on the route from Guwahati to Imphal. The driver will seek assistance from the car AI for this.",
    92: "The driver is looking for wind speed and cloud cover updates for traveling from Delhi to Haridwar. The driver will seek assistance from the car AI for this.",
    93: "The driver wants to get updates on fog conditions and visibility before heading from Jaisalmer to Bikaner. The driver will seek assistance from the car AI for this.",
    94: "The driver needs information about extreme cold weather for a trip from Shimla to Dharamshala. The driver will seek assistance from the car AI for this.",
    95: "The driver is seeking details on rain and temperature conditions for traveling from Mumbai to Surat. The driver will seek assistance from the car AI for this.",
    96: "The driver wants to check the wind chill factor and visibility before heading from Chandigarh to Ambala. The driver will seek assistance from the car AI for this.",
    97: "The driver needs to know if there are any severe weather warnings on the route from Mangalore to Udupi. The driver will seek assistance from the car AI for this.",
    98: "The driver is looking for information about recent weather changes on the drive from Pune to Aurangabad. The driver will seek assistance from the car AI for this.",
    99: "The driver wants to get updates on fog and visibility conditions before traveling from Delhi to Lucknow. The driver will seek assistance from the car AI for this.",
    100: "The driver needs to know if there are any road closures due to rain on the drive from Indore to Bhopal. The driver will seek assistance from the car AI for this."
}


